### PR TITLE
Fix: main process exit in chain.

### PR DESCRIPTION
**Pull request by leeyr338**
- Fix: main process exit in chain.

### CODE REVIEW

**Comment by leeyr338** [comment]
> How?

Keep an infinite loop for main.

**Comment by kaikai1024** [comment]
> Keep an infinite loop for main.

Then?  That's the old `cita-chain` logic, what changed?

**Comment by ouwenkg** [comment]
> > Keep an infinite loop for main.
> 
> Then? That's the old `cita-chain` logic, what changed?

Chain process panic caused by previous remove cache issue.  I mistaked del loop with cache collection.

**Comment by kaikai1024** [comment]
> Chain process panic caused by previous remove cache issue. I mistaked del loop with cache collection.

Got it.

**Pull request merged**
