### PR TITLE
Fix whitespace. [skip ci]

### PR DESCRIPTION
**Pull request by kaikai1024**
#### Description of the Change

Remove the whitespace

#### Applicable Issues

#404

### CODE REVIEW

**Comment by yangby-cryptape** [comment]
You can do better, try `grep -r "[[:space:]]$" [a-zA-Z]*` in the root of this repository.

**Comment by kaikai1024** [comment]
> You can do better, try `grep -r "[[:space:]]$" [a-zA-Z]*` in the root of this repository.

...  :no_mouth:

**Comment by yangby-cryptape** [comment]
Maybe, u should remove the `[skip ci]`?

**Comment by kaikai1024** [comment]
> Maybe, u should remove the `[skip ci]`?

yeah

**Comment by u2** [comment]
> > Maybe, u should remove the `[skip ci]`?
> 
> yeah

It's better to add CI check.

**Comment by kaikai1024** [comment]
It's better to add CI check.

yeah, Maybe a style check.

Will add editorconfig file. check the issue

**Pull request merged**
