### PR TITLE
rewrite extras.rs

### PR DESCRIPTION
**Pull request by ouwenkg**
### Test process

https://gist.github.com/ouwenkg/8b4070be8e289397ce42070b35151f06

### CODE REVIEW

**Comment by kaikai1024** [comment]
I'm a little confused about why do you change the file name? It's difficute to review the changes.

**Comment by ouwenkg** [comment]
> I'm a little confused about why do you change the file name? It's difficute to review the changes.

Sorry for review inconvenience this change brought, but i think  filename `indexes` is more approprite to describe this file's functionality than filename `extras`.

**Comment by leeyr338** [comment]
> > I'm a little confused about why do you change the file name? It's difficute to review the changes.
> 
> Sorry for review inconvenience this change brought, but i think filename `indexes` is more approprite to describe this file's functionality than filename `extras`.

Actually, this is something about **db key encode for types** . So I prefer the file as `db_keys.rs`

**Comment by kaikai1024** [comment]
https://github.com/paritytech/parity-ethereum/blob/master/ethcore/db/src/keys.rs

**Comment by ouwenkg** [comment]
> https://github.com/paritytech/parity-ethereum/blob/master/ethcore/db/src/keys.rs

?

**Comment by ouwenkg** [comment]
> > > I'm a little confused about why do you change the file name? It's difficute to review the changes.
> > 
> > 
> > Sorry for review inconvenience this change brought, but i think filename `indexes` is more approprite to describe this file's functionality than filename `extras`.
> 
> Actually, this is something about **db key encode for types** . So I prefer the file as `db_keys.rs` or `db_indexes.rs` is okay.

Thanks, please check again.

**Comment by kaikai1024** [comment]
> > https://github.com/paritytech/parity-ethereum/blob/master/ethcore/db/src/keys.rs
> 
> ?

Just FYI.

**Comment by ouwenkg** [comment]
> > > https://github.com/paritytech/parity-ethereum/blob/master/ethcore/db/src/keys.rs
> > 
> > 
> > ?
> 
> Just FYI.

Ok, `db_indexes` is ok.

**Pull request merged**
