### PR TITLE
Fix auth crashes

### PR DESCRIPTION
**Pull request by leeyr338**
Fix auth crashes on branch pre-v0.22.0.

### CODE REVIEW

**Comment by kaikai1024** [comment]
Just rebase the pre-v0.22.0 and drop the other commits.
do not change the commits that merged to the develop

**Comment by leeyr338** [comment]
> Just rebase the pre-v0.22.0 and drop the other commits.
> do not change the commits that merged to the develop

Oh, my fault. This operation would be conflicted with`develop`. I will close this `pr` and `cherry-pick` it from develop.

**Comment by kaikai1024** [comment]
> I will close this pr and cherry-pick it from develop.

Just a new pr from your branch to the pre-v0.22.0

**Comment by leeyr338** [comment]
cherry-pick it from `develop`.

**Pull request closed without merging**
