### PR TITLE
Fix executor tolerant staled crashed

### PR DESCRIPTION
**Pull request by ouwenkg**
#### Description
* Fix unwrap usage in proof checking in executor.
* Add one test to ci

Thanks a lot for @keroro520
#### Applicable Issues
#306

### CODE REVIEW

**Comment by kaikai1024** [comment]
Reword the `add to ci test` or fixup it to the `test: add cita_bft_resend.sh`

**Comment by ouwenkg** [comment]
> Reword the `add to ci test` or fixup it to the `test: add cita_bft_resend.sh`

Done!

**Comment by kaikai1024** [comment]
I mean it's an independent commit. you need to clear what test.

**Comment by kaikai1024** [comment]
will squash merging.

**Comment by kaikai1024** [comment]
**will squash merging.**

I will add a label to avoid this.

**Pull request merged**
